DROP TABLE IF EXISTS ARTICLE;

create table ARTICLE
(
	ID			BIGINT auto_increment primary key,
	CATEGORY	VARCHAR(255),
    TITLE       VARCHAR(255),
	CONTENT 	VARCHAR(255),
	AUTHOR		VARCHAR(255),
	LINK		VARCHAR(255),
	ARTICLE_ID	VARCHAR(255),
	REG_DATE	TIMESTAMP,
	UPDATE_DATE	TIMESTAMP
);